AfricaRentCar/Models/voiture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
using System.ComponentModel;
namespace AfricaRentCar.Models
{
    public class voiture
    {
        public int id { get; set; }
        public string marque { get; set; }
        public string modele { get; set; }
        public string type { get; set; }
        public int puissance_fiscale { get; set; }
        public int puissance_chdin { get; set; }
        public string energie { get; set; }
        public string boite_vitesse { get; set; }
        public int nombre_rapport { get; set; }
        public int nombre_cylindres { get; set; }
        public ApplicationUser user_Id { get; set; }
        public Boolean disponibilite { get; set; }
        public float prix { get; set; }
        public string image { get; set; }
        [DisplayName("Upload image")]
        public string url_image { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public string description { get; set; }
       
    }
}

AfricaRentCar/Controllers/voituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AfricaRentCar.Models;
using Microsoft.AspNet.Identity;

namespace AfricaRentCar.Controllers
{
    public class voituresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: voitures
        public ActionResult Index()
        {
            voiture voiture;
            foreach (var item in db.paniers.Include(c=>c.voiture).ToList())
            {
                if ((item.date_location.AddDays(item.nombre_jours).CompareTo(DateTime.Now))>=0)
                {
                    voiture = db.voitures.Find(item.voiture.id);
                    voiture.disponibilite = true;
                    db.Entry(voiture).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            List<voiture> voitures = new List<voiture>();
            foreach (var item in db.voitures.ToList())
            {
                if (item.disponibilite)
                {
                    voitures.Add(item);
                }
            }
            return View(voitures);
        }

        // GET: voitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        [Authorize(Roles = "responsable , admin")]
        // GET: voitures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "responsable , admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(voiture voiture)
        {
            var userId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(voiture.ImageFile.FileName);
                string extension = Path.GetExtension(voiture.ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                voiture.url_image = "/Image/" + filename;
                filename = Path.Combine(Server.MapPath("/Image/"), filename);
                voiture.ImageFile.SaveAs(filename);
                voiture.user_Id = db.Users.Find(userId);
                db.voitures.Add(voiture);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(voiture);
        }
        [Authorize(Roles = "responsable , admin")]
        // GET: voitures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // POST: voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "responsable , admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,marque,modele,type,puissance_fiscale,puissance_chdin,energie,boite_vitesse,nombre_rapport,nombre_cylindres,disponibilite,prix,image,url_image,description")] voiture voiture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(voiture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(voiture);
        }
        [Authorize(Roles = "responsable , admin")]
        // GET: voitures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // POST: voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            voiture voiture = db.voitures.Find(id);
            db.voitures.Remove(voiture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult add(int? id)
        {
            var produit = db.voitures.Find(id);
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            if (User.Identity.IsAuthenticated)
            {
                if (user.EmailConfirmed)
                {
                    panier ligneCommande = new panier();
                    ligneCommande.user = db.Users.Find(userId);
                    ligneCommande.voiture = db.voitures.Find(id);
                    produit.disponibilite = false;
                    ligneCommande.nombre_jours = 1;
                    db.paniers.Add(ligneCommande);
                    db.Entry(produit).State = EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.messager = "Car add to cart successfully !";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("ErrorConfirmation");
                }
            }

            else
            {
                return View("CreateAccount");
            }



        }
        [Authorize(Roles = "responsable")]
        public ActionResult stat()
        {
            int nbVente = 0;
            var userId = User.Identity.GetUserId();
            var nbProduits = db.voitures.Count();
            //int nbMyProduct = 0;
            List<panier> ligneCommandes = db.paniers.Include(l => l.user).Include(l => l.voiture).ToList();
            List<voiture> produits = db.voitures.Include(l => l.user_Id).ToList();
            List<voiture> produitsResponsable = new List<voiture>();
            foreach (var item in produits)
            {
                if (item.user_Id != null)
                {
                    if (item.user_Id.Id == userId)
                    {
                        produitsResponsable.Add(item);
                    }
                }
            }
            foreach (var item in ligneCommandes)
            {
                foreach (var i in produitsResponsable)
                {
                    if (item.voiture.id == i.id)
                    {
                        nbVente += 1;
                    }
                }
            }
            ViewBag.nbMyProduct = produitsResponsable.Count();
            ViewBag.nbProduits = nbProduits;
            ViewBag.nbVente = nbVente;

            return View();

        }
        [Authorize(Roles = "responsable")]
        public ActionResult MyCars()
        {
            List<voiture> produits = db.voitures.Include(l => l.user_Id).ToList();
            List<voiture> mesProduits = new List<voiture>();
            var userId = User.Identity.GetUserId();
            foreach (var item in produits)
            {
                if (item.user_Id != null)
                {
                    if (item.user_Id.Id.Equals(userId))
                    {
                        mesProduits.Add(item);
                    }
                }

            }
            return View(mesProduits);
        }
     
   
   
    }
}

AfricaRentCar/Views/voitures/Create.cshtml
@model AfricaRentCar.Models.voiture

@{
    ViewBag.Title = "Create";
}

<h2>Add Car</h2>
@using (Html.BeginForm("Create", "voitures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.marque, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.marque, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.marque, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.modele, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.modele, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.modele, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.puissance_fiscale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.puissance_fiscale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.puissance_fiscale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.puissance_chdin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.puissance_chdin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.puissance_chdin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.energie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.energie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.energie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.boite_vitesse, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.boite_vitesse, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.boite_vitesse, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nombre_rapport, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre_rapport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre_rapport, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nombre_cylindres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre_cylindres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre_cylindres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.disponibilite, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.disponibilite)
                @Html.ValidationMessageFor(model => model.disponibilite, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.url_image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AfricaRentCar/Views/voitures/Delete.cshtml
@model AfricaRentCar.Models.voiture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>voiture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.marque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modele)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modele)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.puissance_fiscale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.puissance_fiscale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.puissance_chdin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.puissance_chdin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.energie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.energie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.boite_vitesse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.boite_vitesse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre_rapport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_rapport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre_cylindres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_cylindres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.disponibilite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.disponibilite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url_image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AfricaRentCar/Views/voitures/Details.cshtml
@model AfricaRentCar.Models.voiture

@{
    ViewBag.Title = "Details";
}
<link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
<link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
<link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
<link rel="stylesheet" href="/assets/css/Contact-Form-Clean.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
<link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
<link rel="stylesheet" href="/assets/css/Pretty-Footer.css">
<link rel="stylesheet" href="/assets/css/styles.css">
<h2>Details</h2>

<div>
    <h4>voiture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.marque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modele)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modele)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.puissance_fiscale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.puissance_fiscale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.puissance_chdin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.puissance_chdin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.energie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.energie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.boite_vitesse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.boite_vitesse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre_rapport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_rapport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre_cylindres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_cylindres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.disponibilite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.disponibilite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url_image)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.url_image)" width="200" height="200" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("admin") || User.IsInRole("responsable"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.id })
    }
    @Html.ActionLink("Back to List", "Index")
</p>

AfricaRentCar/Views/voitures/Edit.cshtml
@model AfricaRentCar.Models.voiture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>voiture</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.marque, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.marque, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.marque, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.modele, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.modele, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.modele, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.puissance_fiscale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.puissance_fiscale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.puissance_fiscale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.puissance_chdin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.puissance_chdin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.puissance_chdin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.energie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.energie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.energie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.boite_vitesse, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.boite_vitesse, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.boite_vitesse, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nombre_rapport, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre_rapport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre_rapport, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nombre_cylindres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre_cylindres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre_cylindres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.disponibilite, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.disponibilite)
                @Html.ValidationMessageFor(model => model.disponibilite, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.url_image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AfricaRentCar/Views/voitures/stat.cshtml
@using AfricaRentCar.Models
@{
    ViewBag.Title = "Statistique";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Statistique</h2>

@{
    var myChart = new Chart(width: 600, height: 400)
       .AddTitle("Cars Rented")
       .AddSeries(chartType: "column",
          xValue: new[] { "Number of Cars", "Number of rented cars", "My Cars" },
          yValues: new[] { ViewBag.nbProduits, ViewBag.nbVente, ViewBag.nbMyProduct })
       .Write();
}