AfricaRentCar/Controllers/AdminController.cs
using AfricaRentCar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AfricaRentCar.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        public ActionResult AdminLayout()
        {
            var users = db.Users.Count();
            var produits = db.voitures.Count();
            var commande = db.paniers.Count();
            //var factures = db.factures.Count();
            var gaint2020 = 20000;
            var gaint2021 = 22000;
            ViewBag.users = users;
            ViewBag.produits = produits;
            ViewBag.commande = commande;
            ViewBag.factures = 17000;
            ViewBag.gaitn2020 = gaint2020;
            ViewBag.gaint2021 = gaint2021;
            return View();
        }
    }
}

AfricaRentCar/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace AfricaRentCar.Controllers
{
    public class MailController : Controller
    {
        // GET: Mail
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string usermail, string sujet, string objet)
        {
            WebMail.Send(usermail, sujet, objet, null, null, null, true, null, null, null, null, null, null);
            ViewBag.msg = "email was sent successfully...";
            return View();
        }
    }
}

AfricaRentCar/Controllers/facturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AfricaRentCar.Models;
using Microsoft.AspNet.Identity;

namespace AfricaRentCar.Controllers
{
    public class facturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: factures
        [Authorize(Roles = "client")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var fact = db.factures
                .Include(c => c.user).Where(c => c.user.Id == userId)
               .ToList();
            return View(fact);
        }
        [Authorize(Roles = "client")]
        public ActionResult calculFacture()
        {
            facture facture = new facture();
            float somme = 0;
            var userId = User.Identity.GetUserId();
            List<panier> ligneCommandes = db.paniers.Include(l => l.voiture).Include(l => l.user).ToList();
            List<panier> ligneCommandesUser = new List<panier>();
            foreach (var item in ligneCommandes)
            {
                if (item.user != null && item.user.Id.Equals(userId))
                {
                    ligneCommandesUser.Add(item);
                }
                else
                {

                }
            }
            if (userId != null)
            {

                facture.date = DateTime.Now;
                facture.user = db.Users.Find(userId);
                foreach (var item in ligneCommandesUser)
                {
                    somme += item.Montant() + somme;
                }
                facture.somme = somme;
                db.factures.Add(facture);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "client")]
        public ActionResult Pay(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            facture facture = db.factures.Find(id);
            if (facture == null)
            {
                return HttpNotFound();
            }
            facture fact = db.factures.Find(id);
            db.factures.Remove(fact);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET: factures/Details/5
        [Authorize(Roles = "client")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            facture facture = db.factures.Find(id);
            if (facture == null)
            {
                return HttpNotFound();
            }
            return View(facture);
        }

        // GET: factures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: factures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,date,somme")] facture facture)
        {
            if (ModelState.IsValid)
            {
                db.factures.Add(facture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(facture);
        }

        // GET: factures/Edit/5
        [Authorize(Roles = "client")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            facture facture = db.factures.Find(id);
            if (facture == null)
            {
                return HttpNotFound();
            }
            return View(facture);
        }

        // POST: factures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "client")]
        public ActionResult Edit([Bind(Include = "id,date,somme")] facture facture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(facture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(facture);
        }

        // GET: factures/Delete/5
        [Authorize(Roles = "client")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            facture facture = db.factures.Find(id);
            if (facture == null)
            {
                return HttpNotFound();
            }
            return View(facture);
        }

        // POST: factures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "client")]
        public ActionResult DeleteConfirmed(int id)
        {
            facture facture = db.factures.Find(id);
            db.factures.Remove(facture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AfricaRentCar/Controllers/paniersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AfricaRentCar.Models;
using Microsoft.AspNet.Identity;

namespace AfricaRentCar.Controllers
{
    public class paniersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: paniers
        [Authorize(Roles = "client")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            List<panier> ligneCommandes = db.paniers.Include(l => l.voiture).Include(l => l.user).ToList();
            List<panier> ligneCommandesUser = new List<panier>();
            foreach (var item in ligneCommandes)
            {
                if (item.user != null && item.user.Id.Equals(userId))
                {
                    ligneCommandesUser.Add(item);
                }
            }
            return View(ligneCommandesUser);
        }
        // GET: paniers/Details/5
        [Authorize(Roles = "client")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            panier panier = db.paniers.Include(c=>c.voiture).First(a=>a.id==id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }

        // GET: paniers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: paniers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nombre_jours")] panier panier)
        {
            if (ModelState.IsValid)
            {
                db.paniers.Add(panier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(panier);
        }

        // GET: paniers/Edit/5
        [Authorize(Roles = "client")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            panier panier = db.paniers.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }

        // POST: paniers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "client")]
        public ActionResult Edit([Bind(Include = "id,nombre_jours")] panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(panier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(panier);
        }

        // GET: paniers/Delete/5
        [Authorize(Roles = "client")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            panier panier = db.paniers.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }

        // POST: paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "client")]
        public ActionResult DeleteConfirmed(int id)
        {
            panier panier = db.paniers.Find(id);
            db.paniers.Remove(panier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AfricaRentCar/Views/Shared/CreateAccount.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<title>Bakery</title>
<link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
<link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
<link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
<link rel="stylesheet" href="/assets/css/Contact-Form-Clean.css">

<link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
<link rel="stylesheet" href="/assets/css/Pretty-Footer.css">
<link rel="stylesheet" href="/assets/css/styles.css">
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Please create account or login to your account !</h2>

AfricaRentCar/Views/Shared/ErrorConfirmation.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<title>Bakery</title>
<link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
<link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
<link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
<link rel="stylesheet" href="/assets/css/Contact-Form-Clean.css">

<link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
<link rel="stylesheet" href="/assets/css/Pretty-Footer.css">
<link rel="stylesheet" href="/assets/css/styles.css">
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Please confirm your account before shopping, email confirmation was send to you !</h2>

AfricaRentCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Africa Rent Car</title>
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Contact-Form-Clean.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="/assets/css/Pretty-Footer.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <br />
    <br />
    <br />
    <br />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Africa Rent Car</title>
    @Styles.Render("~/assets/css")
    @Scripts.Render("~/assets/js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Africa Rent Car", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.IsInRole("responsable"))
                    {
                        <li>@Html.ActionLink("My Cars", "MyCars", "voitures")</li>
                        <li><a href="https://localhost:44336/voitures/stat" target="_blank">Statistics </a></li>
                    }

                    <li>@Html.ActionLink("Cars List", "Index", "voitures")</li>


                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Admin Space ", "AdminLayout", "Admin")</li>
                    }
                    @if (User.Identity.IsAuthenticated && !User.IsInRole("responsable") && !User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Bill", "Index", "factures")</li>
                        <li>@Html.ActionLink("panier", "Index", "paniers")</li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li>@Html.ActionLink("Change password", "ChangePassword", "Manage")</li>

                    }

                    @if (!User.IsInRole("responsable") && !User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Contact", "Index", "Mail")</li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/assets/bootstrap/js")
    @Scripts.Render("~/assets/bootstrap/css")
    @RenderSection("scripts", required: false)
</body>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 footer-navigation">
                <h3><a href="#">Africa Rent Car</a></h3>
                <p class="links"><a href="#"><strong>technology</strong></a><strong> · </strong><a href="#">Pricing </a><strong> · </strong><a href="#">Order </a><strong> </strong></p>
                <p class="company-name">Africa Rent Car© 2021</p>
            </div>
            <div class="col-md-4 col-sm-6 footer-contacts">
                <div>
                    <span class="fa fa-map-marker footer-contacts-icon"> </span>
                    <p><span class="new-line-span">21 Revolution Street</span> Ariana, Tunisie</p>
                </div>
                <div>
                    <i class="fa fa-phone footer-contacts-icon"></i>
                    <p class="footer-center-info email text-left"> +216 555 123456</p>
                </div>
                <div>
                    <i class="fa fa-envelope footer-contacts-icon"></i>
                    <p> <a href="#" target="_blank">support@company.com</a></p>
                </div>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-4 footer-about">
                <h4>About the company</h4>
                <p>Africa Rent Car was founded in Tunisia in 2021 with the mission of giving great experience of shopping.<br></p>
                <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
            </div>
        </div>
    </div>
</footer>
</html>

<style>
    #myInput {
        width: 100%;
        border: 1px solid grey;
        padding: 5px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        background: #f1f1f1;
        height: 20%;
    }

    .btn {
        width: 25%;
    }

    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    #promo {
        background: url(/assets/img/la-vie-en-Golf.jpg);
    }
</style>